# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Projects and the Future
tagline:          Projects and the Future
url:              http://eduardo-robles.github.io/
paginate:         1
baseurl:          /
author:
  name:           Eduardo Robles
  url:            https://twitter.com/hardrived
  email:          eduardorobles02@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/eduardo-robles 

# This is the list of pages to incldue in the header of the website.
pages_list: {'About':'/about','Archive':'/archive','Connect':'/connect','Feed':'/atom.xml'}
