baseURL = "https://eduardo-robles.github.io/"
title   = "Eduardo Robles Site"
languageCode = "en-us"
timeZone = "America/Chicago"
theme = "smol"
canonifyurls = true
# Parameters
[params]
    author = "Eduardo Robles"
    authorGilab = "https://gitlab.com/tacosandlinux"
    mainSections = ["posts"]
    Subtitle = "Hola Mundo 🌮"
    dateFmt = "02.01.2006"

[markup.goldmark.renderer]
  unsafe = true

# Header
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/pages/about"
    weight     = -100
  [[menu.main]]
    identifier = "Links"
    name       = "Links"
    url        = "/pages/links"
    weight     = -100
  [[menu.main]]
    identifier = "Contribute"
    name       = "Contribute"
    url        = "/pages/contribute"
    weight     = -100
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = -100
  [[menu.main]]
    identifier = "videos"
    name       = "Videos"
    url        = "/pages/videos/"
    weight     = -100
  [[menu.main]]
    identifier = "rss"
    name       = "RSS"
    url        = "/index.xml"
    weight     = 0

# Footer
  [[menu.footer]]
        name = "Gitlab"
        url = "https://gitlab.com/tacosandlinux"
        weight = 1

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/tacosandlinux"
        weight = 2

    [[menu.footer]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/hello-im-eduardo/"
        weight = 3
